// <auto-generated />
using System;
using Du_An_Web_Ban_Khoa_Hoc.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Du_An_Web_Ban_Khoa_Hoc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseTag", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("TagID");

                    b.HasKey("CourseId", "TagId")
                        .HasName("PK__CourseTa__1F7ABE2387AE6C57");

                    b.HasIndex("TagId");

                    b.ToTable("CourseTags", (string)null);
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.Property<DateTime?>("LastLogin")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId")
                        .HasName("PK__Admins__719FE4E80FC60F87");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AssignmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Assignme__32499E576B63C417");

                    b.HasIndex("CourseId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Banner", b =>
                {
                    b.Property<int>("BannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BannerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BannerId"));

                    b.Property<DateTime?>("EndDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("ImageURL");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("LinkURL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Title")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("BannerId")
                        .HasName("PK__Banners__32E86A314589A283");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CartId")
                        .HasName("PK__Carts__51BCD7971AB4C295");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("CartItemId")
                        .HasName("PK__CartItem__488B0B2A6A3D72E3");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "CartId", "CourseId" }, "UQ_CartItem_CourseInCart")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A2B27DD31B8");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Certificate", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CertificateID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateId"));

                    b.Property<string>("CertificateUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("CertificateURL");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CertificateId")
                        .HasName("PK__Certific__BBF8A7E1B8408C2C");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("vi");

                    b.Property<string>("LearningOutcomes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("beginner");

                    b.Property<string>("Prerequisites")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewVideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("PreviewVideoURL");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("draft");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ThumbnailURL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("CourseId")
                        .HasName("PK__Courses__C92D7187B2E007ED");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Courses_CategoryID");

                    b.HasIndex(new[] { "InstructorId" }, "IX_Courses_InstructorID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnrollmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<DateTime>("EnrollDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("active");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Enrollme__7F6877FBB6766D66");

                    b.HasIndex(new[] { "CourseId" }, "IX_Enrollments_CourseID");

                    b.HasIndex(new[] { "UserId" }, "IX_Enrollments_UserID");

                    b.HasIndex(new[] { "CourseId", "UserId" }, "UQ_Enrollment_UserCourse")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.EnrollmentLog", b =>
                {
                    b.Property<int>("EnrollmentLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnrollmentLogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("EnrollmentID");

                    b.HasKey("EnrollmentLogId")
                        .HasName("PK__Enrollme__405B8241D73E313E");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("EnrollmentLogs");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<byte?>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDF618689E52");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("FileSizeBigint")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("FileId")
                        .HasName("PK__Files__6F0F989F4FFD5F8B");

                    b.HasIndex("CourseId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Earnings")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Education")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Expertise")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("FacebookURL");

                    b.Property<DateTime?>("LastPayoutDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("LinkedInURL");

                    b.Property<string>("PayoutAccount")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PayoutMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("RatingAverage")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<int>("TotalCourses")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pending");

                    b.Property<string>("Xurl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("XURL");

                    b.Property<string>("YouTubeUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("YouTubeURL");

                    b.HasKey("InstructorId")
                        .HasName("PK__Instruct__9D010B7B103D39CE");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.InstructorProgress", b =>
                {
                    b.Property<int>("InstructorProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstructorProgressID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorProgressId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<int>("StudentCompleted")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("InstructorProgressId")
                        .HasName("PK__Instruct__8838A63238AF3FB6");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "InstructorId", "CourseId" }, "UQ_InstructorCourse")
                        .IsUnique();

                    b.ToTable("InstructorProgress", (string)null);
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LessonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("int");

                    b.Property<int?>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("FileID");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("VideoURL");

                    b.HasKey("LessonId")
                        .HasName("PK__Lessons__B084ACB046EAF7F5");

                    b.HasIndex("FileId");

                    b.HasIndex(new[] { "CourseId", "SortOrder" }, "IX_Lessons_CourseID_Sort");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Log", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LogId")
                        .HasName("PK__Logs__5E5499A801B25F6A");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MessageType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("ReceiverID");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SenderID");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__C87C037C2B52313F");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pending");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAF0B4298FD");

                    b.HasIndex(new[] { "UserId" }, "IX_Orders_UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D30C3FBDB465");

                    b.HasIndex("CourseId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<DateTime?>("PaidAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pending");

                    b.Property<string>("RawResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TransactionID");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A587772EBF5");

                    b.HasIndex("OrderId");

                    b.HasIndex(new[] { "TransactionId" }, "IX_Payments_TransactionID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.PaymentVerification", b =>
                {
                    b.Property<int>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VerificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerificationId"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("verified");

                    b.Property<DateTime>("VerifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("VerificationId")
                        .HasName("PK__PaymentV__306D4927D8372E41");

                    b.HasIndex("PaymentId");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("PaymentVerifications");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Payout", b =>
                {
                    b.Property<int>("PayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PayoutID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayoutId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pending");

                    b.HasKey("PayoutId")
                        .HasName("PK__Payouts__35C3DFAED96BD9F9");

                    b.HasIndex("InstructorId");

                    b.ToTable("Payouts");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Progress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgressID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("EnrollmentID");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("LessonID");

                    b.HasKey("ProgressId")
                        .HasName("PK__Progress__BAE29C85CC932821");

                    b.HasIndex("LessonId");

                    b.HasIndex(new[] { "EnrollmentId", "LessonId" }, "UQ_Progress_EnrollLesson")
                        .IsUnique();

                    b.ToTable("Progress", (string)null);
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuestionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("AssignmentID");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Points")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QuestionId")
                        .HasName("PK__Question__0DC06F8CE680CC69");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<string>("ReportData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ReportId")
                        .HasName("PK__Reports__D5BD48E5592DFE4B");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79AE5463BDAA");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Reveiws_CourseID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A15B111BC");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B61609B917CF2")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseID");

                    b.Property<DateTime?>("EndTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("InstructorID");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("StartTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Schedule__9C8A5B6937DC6620");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("CompletedCourses")
                        .HasColumnType("int");

                    b.Property<int>("EnrollmentCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastActive")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("TotalCertificates")
                        .HasColumnType("int");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52A792FF069C9");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubmissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("AssignmentID");

                    b.Property<int?>("FileId")
                        .HasColumnType("int")
                        .HasColumnName("FileID");

                    b.Property<DateTime?>("GradedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("GradedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("SubmissionId")
                        .HasName("PK__Submissi__449EE1052B97BD26");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("FileId");

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TagID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TagId")
                        .HasName("PK__Tags__657CFA4C561DC033");

                    b.HasIndex(new[] { "Slug" }, "UQ__Tags__BC7B5FB6D12050AF")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("AvatarURL");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACC767A2B3");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534C8EC976A")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK__UserRole__AF27604F8E3B2630");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("CourseTag", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourseTags_Courses");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourseTags_Tags");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Admin", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "AdminNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("Du_An_Web_Ban_Khoa_Hoc.Models.Admin", "AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Admins_Users");

                    b.Navigation("AdminNavigation");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Assignment", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Assignments_Courses");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Cart", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Carts_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.CartItem", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Carts");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Course", "Course")
                        .WithMany("CartItems")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Courses");

                    b.Navigation("Cart");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Category", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Categories_Parent");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Certificate", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Course", "Course")
                        .WithMany("Certificates")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Certificates_Courses");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Certificates_Users");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Course", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Courses_Category");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Courses_Instructor");

                    b.Navigation("Category");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Enrollment", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Enrollments_Courses");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Enrollments_Users");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.EnrollmentLog", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Enrollment", "Enrollment")
                        .WithMany("EnrollmentLogs")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EnrollmentLogs_Enrollments");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Feedback", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Feedbacks_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.File", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Course", "Course")
                        .WithMany("Files")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Files_Courses");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "UploadedByNavigation")
                        .WithMany("Files")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Files_Users");

                    b.Navigation("Course");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Instructor", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "InstructorNavigation")
                        .WithOne("Instructor")
                        .HasForeignKey("Du_An_Web_Ban_Khoa_Hoc.Models.Instructor", "InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Instructors_Users");

                    b.Navigation("InstructorNavigation");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.InstructorProgress", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Course", "Course")
                        .WithMany("InstructorProgresses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InstructorProgress_Courses");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Instructor", "Instructor")
                        .WithMany("InstructorProgresses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InstructorProgress_Instructors");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Lesson", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Lessons_Courses");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.File", "File")
                        .WithMany("Lessons")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Lessons_Files");

                    b.Navigation("Course");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Log", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Logs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Message", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "Receiver")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .IsRequired()
                        .HasConstraintName("FK_Messages_Receiver");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Messages_Sender");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Order", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Orders_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.OrderDetail", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Course", "Course")
                        .WithMany("OrderDetails")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Courses");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Orders");

                    b.Navigation("Course");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Payment", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Payments_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.PaymentVerification", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Payment", "Payment")
                        .WithMany("PaymentVerifications")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentVerifications_Payments");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "VerifiedByNavigation")
                        .WithMany("PaymentVerifications")
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_PaymentVerifications_Admins");

                    b.Navigation("Payment");

                    b.Navigation("VerifiedByNavigation");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Payout", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Instructor", "Instructor")
                        .WithMany("Payouts")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payouts_Instructors");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Progress", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Enrollment", "Enrollment")
                        .WithMany("Progresses")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Progress_Enrollments");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Lesson", "Lesson")
                        .WithMany("Progresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Progress_Lessons");

                    b.Navigation("Enrollment");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Question", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Assignment", "Assignment")
                        .WithMany("Questions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Questions_Assignments");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Report", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "GeneratedByNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Reports_Admins");

                    b.Navigation("GeneratedByNavigation");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Review", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Courses");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Users");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Schedule", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Course", "Course")
                        .WithMany("Schedules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Schedules_Courses");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Instructor", "Instructor")
                        .WithMany("Schedules")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Schedules_Instructors");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Student", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "StudentNavigation")
                        .WithOne("Student")
                        .HasForeignKey("Du_An_Web_Ban_Khoa_Hoc.Models.Student", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Students_Users");

                    b.Navigation("StudentNavigation");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Submission", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Submissions_Assignments");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.File", "File")
                        .WithMany("Submissions")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Submissions_Files");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Submissions_Users");

                    b.Navigation("Assignment");

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.UserRole", b =>
                {
                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("Du_An_Web_Ban_Khoa_Hoc.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Assignment", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Category", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("CartItems");

                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");

                    b.Navigation("Files");

                    b.Navigation("InstructorProgresses");

                    b.Navigation("Lessons");

                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Enrollment", b =>
                {
                    b.Navigation("EnrollmentLogs");

                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.File", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Instructor", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("InstructorProgresses");

                    b.Navigation("Payouts");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Lesson", b =>
                {
                    b.Navigation("Progresses");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Payment", b =>
                {
                    b.Navigation("PaymentVerifications");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Du_An_Web_Ban_Khoa_Hoc.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Carts");

                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");

                    b.Navigation("Feedbacks");

                    b.Navigation("Files");

                    b.Navigation("Instructor");

                    b.Navigation("Logs");

                    b.Navigation("MessageReceivers");

                    b.Navigation("MessageSenders");

                    b.Navigation("Orders");

                    b.Navigation("PaymentVerifications");

                    b.Navigation("Reports");

                    b.Navigation("Reviews");

                    b.Navigation("Student");

                    b.Navigation("Submissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
